services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:80"
    networks:
      - conformance-net
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - ALLOWED_ORIGINS=http://localhost:3001
      - AZURE_AD_AUTH_ENABLED=false
      - FHIR_VALIDATOR_ENDPOINT=
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} #escaped characters better handled in .env
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=

    networks:
      - conformance-net

networks:
  conformance-net:
    driver: bridge
